title: "Edo W. Almeida"
description: "Professional website"

url: "https://edoalmeida.github.io"
baseurl: "/professional"

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-include-cache

minimal_mistakes_skin: "dirt"
